apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-challenge-app
  labels:
    app: devops-challenge-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devops-challenge-app
  template:
    metadata:
      labels:
        app: devops-challenge-app
    spec:
      containers:
      - name: devops-challenge-app
        image: devops-challenge-app:dev
        imagePullPolicy: IfNotPresent  # For OrbStack local images
        ports:
        - containerPort: 8080
          name: http
        envFrom:
        - configMapRef:
            name: devops-challenge-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "150Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
